### Health Check
GET http://localhost:3001/health
Content-Type: application/json

### Criar Notificação
POST http://localhost:3001/notifications
Content-Type: application/json

{
  "title": "TESTEI TUDO AGORA",
  "message": "BACKEND"
}

### Listar Notificações
GET http://localhost:3001/notifications
Content-Type: application/json

### Atualziar Status
PATCH http://localhost:3001/notifications/{id}
Content-Type: application/json

{
  "status": "SENT"
}